<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace englishauction;

use \php\Boot;

class AuctionModel {
	/**
	 * @var int
	 */
	public $end;
	/**
	 * @var string
	 */
	public $id;
	/**
	 * @var float
	 */
	public $priceIncrement;
	/**
	 * @var float
	 */
	public $reservePrice;
	/**
	 * @var int
	 */
	public $start;
	/**
	 * @var float
	 */
	public $startingPrice;

	/**
	 * @return void
	 */
	public function __construct () {
	}
}

Boot::registerClass(AuctionModel::class, 'englishauction.AuctionModel');
