<?php
/**
 * Generated by Haxe 4.1.1
 */

namespace englishauction;

use \php\Boot;

class BidModel {
	/**
	 * @var string
	 */
	public $auctionId;
	/**
	 * @var string
	 */
	public $id;
	/**
	 * @var float
	 */
	public $price;
	/**
	 * @var string
	 */
	public $userId;

	/**
	 * @return void
	 */
	public function __construct () {
	}
}

Boot::registerClass(BidModel::class, 'englishauction.BidModel');
